"""Bookings, schedule slots, tasks, notifications, calls and operator KPI models."""

from __future__ import annotations

from datetime import date, datetime

from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, IdMixin, SoftDeleteMixin, TimestampMixin
from app.models.crm import Lead
from app.models.enums import (
    BookingPurpose,
    BookingStatus,
    CallDirection,
    NotificationLevel,
    Sentiment,
    TaskPriority,
    TaskStatus,
    TaskType,
)
from app.models.organization import Branch, Service, User


class Booking(Base, IdMixin, TimestampMixin, SoftDeleteMixin):
    """An appointment / trial lesson / test drive booked for a lead."""

    __tablename__ = "bookings"

    lead_id: Mapped[int] = mapped_column(ForeignKey("leads.id"), nullable=False, index=True)
    service_id: Mapped[int | None] = mapped_column(ForeignKey("services.id"), nullable=True)
    branch_id: Mapped[int | None] = mapped_column(ForeignKey("branches.id"), nullable=True)
    specialist_id: Mapped[int | None] = mapped_column(ForeignKey("users.id"), nullable=True)
    purpose: Mapped[str] = mapped_column(String(40), default=BookingPurpose.GENERAL_MEETING)
    starts_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, index=True)
    ends_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    duration_minutes: Mapped[int] = mapped_column(Integer, default=30)
    status: Mapped[str] = mapped_column(String(24), default=BookingStatus.PENDING, index=True)
    created_channel: Mapped[str] = mapped_column(String(24), default="manual")
    created_by_ai: Mapped[bool] = mapped_column(Boolean, default=False)
    confirmation_sent_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    reminder_sent_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    confirmed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    cancelled_reason: Mapped[str] = mapped_column(String(200), default="")
    note: Mapped[str] = mapped_column(Text, default="")
    created_by_id: Mapped[int | None] = mapped_column(ForeignKey("users.id"), nullable=True)

    lead: Mapped[Lead] = relationship(lazy="joined")
    service: Mapped[Service | None] = relationship(lazy="joined")
    branch: Mapped[Branch | None] = relationship(lazy="joined")
    specialist: Mapped[User | None] = relationship(lazy="joined", foreign_keys=[specialist_id])


class ScheduleSlot(Base, IdMixin, TimestampMixin):
    """Working-hours template used to offer only free slots."""

    __tablename__ = "schedule_slots"

    branch_id: Mapped[int | None] = mapped_column(ForeignKey("branches.id"), nullable=True)
    specialist_id: Mapped[int | None] = mapped_column(ForeignKey("users.id"), nullable=True)
    weekday: Mapped[int] = mapped_column(Integer, default=0)
    start_time: Mapped[str] = mapped_column(String(5), default="09:00")
    end_time: Mapped[str] = mapped_column(String(5), default="18:00")
    slot_minutes: Mapped[int] = mapped_column(Integer, default=30)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)


class Task(Base, IdMixin, TimestampMixin, SoftDeleteMixin):
    """Follow-up task generated by rules or created manually."""

    __tablename__ = "tasks"

    lead_id: Mapped[int | None] = mapped_column(ForeignKey("leads.id"), nullable=True, index=True)
    booking_id: Mapped[int | None] = mapped_column(ForeignKey("bookings.id"), nullable=True)
    assignee_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id"), nullable=True, index=True
    )
    created_by_id: Mapped[int | None] = mapped_column(ForeignKey("users.id"), nullable=True)
    task_type: Mapped[str] = mapped_column(String(32), default=TaskType.OTHER)
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[str] = mapped_column(Text, default="")
    due_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True, index=True)
    status: Mapped[str] = mapped_column(String(24), default=TaskStatus.OPEN, index=True)
    priority: Mapped[str] = mapped_column(String(16), default=TaskPriority.NORMAL)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    result_comment: Mapped[str] = mapped_column(Text, default="")
    auto_rule: Mapped[str] = mapped_column(String(64), default="")

    lead: Mapped[Lead | None] = relationship(lazy="joined")
    assignee: Mapped[User | None] = relationship(lazy="joined", foreign_keys=[assignee_id])


class Notification(Base, IdMixin):
    """Entry of the desktop notification centre."""

    __tablename__ = "notifications"

    user_id: Mapped[int | None] = mapped_column(ForeignKey("users.id"), nullable=True, index=True)
    lead_id: Mapped[int | None] = mapped_column(ForeignKey("leads.id"), nullable=True)
    conversation_id: Mapped[int | None] = mapped_column(
        ForeignKey("conversations.id"), nullable=True
    )
    level: Mapped[str] = mapped_column(String(16), default=NotificationLevel.INFO, index=True)
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    body: Mapped[str] = mapped_column(Text, default="")
    category: Mapped[str] = mapped_column(String(48), default="general")
    is_read: Mapped[bool] = mapped_column(Boolean, default=False, index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, index=True)


class Call(Base, IdMixin, TimestampMixin, SoftDeleteMixin):
    """Telephony call record."""

    __tablename__ = "calls"

    lead_id: Mapped[int | None] = mapped_column(ForeignKey("leads.id"), nullable=True, index=True)
    operator_id: Mapped[int | None] = mapped_column(ForeignKey("users.id"), nullable=True)
    direction: Mapped[str] = mapped_column(String(16), default=CallDirection.OUTBOUND)
    phone: Mapped[str] = mapped_column(String(32), default="")
    provider: Mapped[str] = mapped_column(String(48), default="demo")
    external_id: Mapped[str] = mapped_column(String(120), default="")
    started_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, index=True)
    ended_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    duration_seconds: Mapped[int] = mapped_column(Integer, default=0)
    outcome: Mapped[str] = mapped_column(String(32), default="no_answer", index=True)
    recording_path: Mapped[str] = mapped_column(String(512), default="")
    note: Mapped[str] = mapped_column(Text, default="")
    score_delta: Mapped[int] = mapped_column(Integer, default=0)

    lead: Mapped[Lead | None] = relationship(lazy="joined")
    operator: Mapped[User | None] = relationship(lazy="joined", foreign_keys=[operator_id])
    transcript: Mapped[CallTranscript | None] = relationship(
        back_populates="call", cascade="all, delete-orphan", uselist=False, lazy="selectin"
    )
    analysis: Mapped[CallAnalysis | None] = relationship(
        back_populates="call", cascade="all, delete-orphan", uselist=False, lazy="selectin"
    )


class CallTranscript(Base, IdMixin, TimestampMixin):
    """Speech-to-text output for a call."""

    __tablename__ = "call_transcripts"

    call_id: Mapped[int] = mapped_column(
        ForeignKey("calls.id", ondelete="CASCADE"), nullable=False, unique=True
    )
    provider: Mapped[str] = mapped_column(String(48), default="demo")
    language: Mapped[str] = mapped_column(String(8), default="uz")
    text: Mapped[str] = mapped_column(Text, default="")
    confidence: Mapped[float] = mapped_column(Float, default=0.0)

    call: Mapped[Call] = relationship(back_populates="transcript")


class CallAnalysis(Base, IdMixin, TimestampMixin):
    """LLM analysis of a call transcript."""

    __tablename__ = "call_analyses"

    call_id: Mapped[int] = mapped_column(
        ForeignKey("calls.id", ondelete="CASCADE"), nullable=False, unique=True
    )
    summary: Mapped[str] = mapped_column(Text, default="")
    customer_need: Mapped[str] = mapped_column(Text, default="")
    objections: Mapped[str] = mapped_column(Text, default="")
    operator_mistakes: Mapped[str] = mapped_column(Text, default="")
    next_best_action: Mapped[str] = mapped_column(Text, default="")
    sentiment: Mapped[str] = mapped_column(String(16), default=Sentiment.NEUTRAL)
    quality_score: Mapped[int] = mapped_column(Integer, default=0)
    got_phone: Mapped[bool] = mapped_column(Boolean, default=False)
    got_purpose: Mapped[bool] = mapped_column(Boolean, default=False)
    got_booking: Mapped[bool] = mapped_column(Boolean, default=False)
    alert_raised: Mapped[bool] = mapped_column(Boolean, default=False)

    call: Mapped[Call] = relationship(back_populates="analysis")


class OperatorPerformanceSnapshot(Base, IdMixin, TimestampMixin):
    """Daily aggregated KPI row for one operator."""

    __tablename__ = "operator_performance_snapshots"

    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), nullable=False, index=True)
    snapshot_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    leads_handled: Mapped[int] = mapped_column(Integer, default=0)
    first_response_avg_sec: Mapped[int] = mapped_column(Integer, default=0)
    response_avg_sec: Mapped[int] = mapped_column(Integer, default=0)
    bookings: Mapped[int] = mapped_column(Integer, default=0)
    arrivals: Mapped[int] = mapped_column(Integer, default=0)
    sales: Mapped[int] = mapped_column(Integer, default=0)
    revenue: Mapped[float] = mapped_column(Float, default=0.0)
    missed_followups: Mapped[int] = mapped_column(Integer, default=0)
    call_quality_avg: Mapped[float] = mapped_column(Float, default=0.0)
    ai_suggestion_usage: Mapped[float] = mapped_column(Float, default=0.0)
    sentiment_positive_ratio: Mapped[float] = mapped_column(Float, default=0.0)
