"""boshlangich sxema

Revision ID: 50118e82c331
Revises: 
Create Date: 2026-08-24 19:44:37.505336
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.LargeBinary(length=16), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_event_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_time', ['occurred_at'], unique=False)

    op.create_table('catalog_category',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['catalog_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logical_timestamp', sa.String(length=64), nullable=False),
    sa.Column('device_sequence', sa.BigInteger(), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('causation_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('projection_attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'device_sequence', name='uq_event_device_seq'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.create_index('ix_event_aggregate', ['aggregate_type', 'aggregate_id'], unique=False)
        batch_op.create_index('ix_event_tenant_seq', ['tenant_id', 'device_id', 'device_sequence'], unique=False)
        batch_op.create_index('ix_event_type_time', ['event_type', 'occurred_at'], unique=False)
        batch_op.create_index('ix_event_unapplied', ['applied_at'], unique=False)

    op.create_table('inv_stock_snapshot',
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('computed_through', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('warehouse_id', 'product_id')
    )
    op.create_table('org_organization',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('tax_id', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_territory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_checkpoint',
    sa.Column('peer_device_id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('last_applied_sequence', sa.BigInteger(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_digest_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('protocol_version', sa.String(length=10), nullable=False),
    sa.Column('missing_ranges', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('peer_device_id')
    )
    op.create_table('sync_conflict',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.String(length=64), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=True),
    sa.Column('local_event_id', sa.String(length=36), nullable=True),
    sa.Column('remote_event_id', sa.String(length=36), nullable=True),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('local_value', sa.Text(), nullable=True),
    sa.Column('remote_value', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_conflict', schema=None) as batch_op:
        batch_op.create_index('ix_conflict_aggregate', ['aggregate_type', 'aggregate_id'], unique=False)
        batch_op.create_index('ix_conflict_open', ['status', 'detected_at'], unique=False)

    op.create_table('sync_dead_letter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('sender_device_id', sa.LargeBinary(length=16), nullable=True),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('raw_size_bytes', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_dead_letter', schema=None) as batch_op:
        batch_op.create_index('ix_dead_letter_open', ['resolved_at', 'occurred_at'], unique=False)

    op.create_table('sync_device_sequence',
    sa.Column('device_id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('next_sequence', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('sync_epoch_key',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('root_secret_wrapped', sa.LargeBinary(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('epoch', 'key_id', name='uq_epoch_key')
    )
    with op.batch_alter_table('sync_epoch_key', schema=None) as batch_op:
        batch_op.create_index('ix_epoch_current', ['is_current'], unique=False)

    op.create_table('sync_inbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('sender_device_id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('sender_sequence', sa.BigInteger(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('sync_inbox', schema=None) as batch_op:
        batch_op.create_index('ix_inbox_sender', ['sender_device_id', 'sender_sequence'], unique=False)

    op.create_table('sync_peer_device',
    sa.Column('device_id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('tenant_id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('sign_public_key', sa.LargeBinary(), nullable=False),
    sa.Column('kem_public_key', sa.LargeBinary(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('last_applied_sequence', sa.BigInteger(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_full_replica', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    with op.batch_alter_table('sync_peer_device', schema=None) as batch_op:
        batch_op.create_index('ix_peer_state', ['state'], unique=False)

    op.create_table('sync_replay_window',
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('highest_sequence', sa.BigInteger(), nullable=False),
    sa.Column('bitmap', sa.LargeBinary(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('epoch', 'device_id')
    )
    op.create_table('catalog_product',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('barcode', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('pack_size', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('purchase_price', sa.BigInteger(), nullable=False),
    sa.Column('retail_price', sa.BigInteger(), nullable=False),
    sa.Column('wholesale_price', sa.BigInteger(), nullable=False),
    sa.Column('agent_price', sa.BigInteger(), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('image_path', sa.String(length=400), nullable=True),
    sa.Column('field_versions', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['catalog_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('catalog_product', schema=None) as batch_op:
        batch_op.create_index('ix_product_active', ['is_active'], unique=False)
        batch_op.create_index('ix_product_barcode', ['barcode'], unique=False)
        batch_op.create_index('ix_product_name', ['name'], unique=False)

    op.create_table('org_branch',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['org_organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('territory_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['territory_id'], ['org_territory.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sync_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('partition', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_log.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('sync_outbox', schema=None) as batch_op:
        batch_op.create_index('ix_outbox_pending', ['state', 'next_attempt_at'], unique=False)

    op.create_table('catalog_batch',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('batch_code', sa.String(length=60), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'batch_code', name='uq_batch_product_code')
    )
    with op.batch_alter_table('catalog_batch', schema=None) as batch_op:
        batch_op.create_index('ix_batch_expiry', ['expires_on'], unique=False)

    op.create_table('crm_customer',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('territory_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_agent_id', sa.String(length=36), nullable=True),
    sa.Column('price_tier', sa.String(length=20), nullable=False),
    sa.Column('credit_limit', sa.BigInteger(), nullable=False),
    sa.Column('payment_term_days', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('field_versions', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['org_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['territory_id'], ['org_territory.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('crm_customer', schema=None) as batch_op:
        batch_op.create_index('ix_customer_agent', ['assigned_agent_id'], unique=False)
        batch_op.create_index('ix_customer_name', ['name'], unique=False)
        batch_op.create_index('ix_customer_territory', ['territory_id'], unique=False)

    op.create_table('field_route',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('route_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['org_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_route', schema=None) as batch_op:
        batch_op.create_index('ix_route_agent_date', ['agent_id', 'route_date'], unique=False)

    op.create_table('org_cash_register',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['org_branch.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_warehouse',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['org_branch.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('field_visit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('photo_path', sa.String(length=400), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['org_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['field_route.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_visit', schema=None) as batch_op:
        batch_op.create_index('ix_visit_agent_date', ['agent_id', 'started_at'], unique=False)

    op.create_table('fin_payment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('cash_register_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reverses_payment_id', sa.String(length=36), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.Column('source_event_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cash_register_id'], ['org_cash_register.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reverses_payment_id'], ['fin_payment.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('fin_payment', schema=None) as batch_op:
        batch_op.create_index('ix_payment_customer', ['customer_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_payment_register', ['cash_register_id', 'occurred_at'], unique=False)

    op.create_table('inv_movement',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_cost', sa.BigInteger(), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_event_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['catalog_batch.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['org_warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_movement', schema=None) as batch_op:
        batch_op.create_index('ix_movement_reference', ['reference_type', 'reference_id'], unique=False)
        batch_op.create_index('ix_movement_stock', ['warehouse_id', 'product_id', 'occurred_at'], unique=False)

    op.create_table('sales_order',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_due', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.BigInteger(), nullable=False),
    sa.Column('discount_total', sa.BigInteger(), nullable=False),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.Column('paid_total', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('origin_device_id', sa.LargeBinary(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['org_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['org_warehouse.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.create_index('ix_order_agent', ['agent_id'], unique=False)
        batch_op.create_index('ix_order_customer', ['customer_id'], unique=False)
        batch_op.create_index('ix_order_date', ['ordered_at'], unique=False)
        batch_op.create_index('ix_order_state_date', ['state', 'ordered_at'], unique=False)

    op.create_table('fin_payment_allocation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['fin_payment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'order_id', name='uq_allocation_payment_order')
    )
    op.create_table('sales_order_line',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.BigInteger(), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.BigInteger(), nullable=False),
    sa.Column('returned_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_product.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_order_line', schema=None) as batch_op:
        batch_op.create_index('ix_order_line_product', ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_line', schema=None) as batch_op:
        batch_op.drop_index('ix_order_line_product')

    op.drop_table('sales_order_line')
    op.drop_table('fin_payment_allocation')
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.drop_index('ix_order_state_date')
        batch_op.drop_index('ix_order_date')
        batch_op.drop_index('ix_order_customer')
        batch_op.drop_index('ix_order_agent')

    op.drop_table('sales_order')
    with op.batch_alter_table('inv_movement', schema=None) as batch_op:
        batch_op.drop_index('ix_movement_stock')
        batch_op.drop_index('ix_movement_reference')

    op.drop_table('inv_movement')
    with op.batch_alter_table('fin_payment', schema=None) as batch_op:
        batch_op.drop_index('ix_payment_register')
        batch_op.drop_index('ix_payment_customer')

    op.drop_table('fin_payment')
    with op.batch_alter_table('field_visit', schema=None) as batch_op:
        batch_op.drop_index('ix_visit_agent_date')

    op.drop_table('field_visit')
    op.drop_table('org_warehouse')
    op.drop_table('org_cash_register')
    with op.batch_alter_table('field_route', schema=None) as batch_op:
        batch_op.drop_index('ix_route_agent_date')

    op.drop_table('field_route')
    with op.batch_alter_table('crm_customer', schema=None) as batch_op:
        batch_op.drop_index('ix_customer_territory')
        batch_op.drop_index('ix_customer_name')
        batch_op.drop_index('ix_customer_agent')

    op.drop_table('crm_customer')
    with op.batch_alter_table('catalog_batch', schema=None) as batch_op:
        batch_op.drop_index('ix_batch_expiry')

    op.drop_table('catalog_batch')
    with op.batch_alter_table('sync_outbox', schema=None) as batch_op:
        batch_op.drop_index('ix_outbox_pending')

    op.drop_table('sync_outbox')
    op.drop_table('org_user')
    op.drop_table('org_branch')
    with op.batch_alter_table('catalog_product', schema=None) as batch_op:
        batch_op.drop_index('ix_product_name')
        batch_op.drop_index('ix_product_barcode')
        batch_op.drop_index('ix_product_active')

    op.drop_table('catalog_product')
    op.drop_table('sync_replay_window')
    with op.batch_alter_table('sync_peer_device', schema=None) as batch_op:
        batch_op.drop_index('ix_peer_state')

    op.drop_table('sync_peer_device')
    with op.batch_alter_table('sync_inbox', schema=None) as batch_op:
        batch_op.drop_index('ix_inbox_sender')

    op.drop_table('sync_inbox')
    with op.batch_alter_table('sync_epoch_key', schema=None) as batch_op:
        batch_op.drop_index('ix_epoch_current')

    op.drop_table('sync_epoch_key')
    op.drop_table('sync_device_sequence')
    with op.batch_alter_table('sync_dead_letter', schema=None) as batch_op:
        batch_op.drop_index('ix_dead_letter_open')

    op.drop_table('sync_dead_letter')
    with op.batch_alter_table('sync_conflict', schema=None) as batch_op:
        batch_op.drop_index('ix_conflict_open')
        batch_op.drop_index('ix_conflict_aggregate')

    op.drop_table('sync_conflict')
    op.drop_table('sync_checkpoint')
    op.drop_table('org_territory')
    op.drop_table('org_organization')
    op.drop_table('inv_stock_snapshot')
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_index('ix_event_unapplied')
        batch_op.drop_index('ix_event_type_time')
        batch_op.drop_index('ix_event_tenant_seq')
        batch_op.drop_index('ix_event_aggregate')

    op.drop_table('event_log')
    op.drop_table('catalog_category')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_time')
        batch_op.drop_index('ix_audit_entity')
        batch_op.drop_index('ix_audit_action')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
