"""§3 — konstantalar. Domen yorliqlari ASCII baytlar, aynan spec'dagidek."""

from __future__ import annotations

VERSIYA = "3.0.0"

# §3.1 domen yorliqlari
L_HEADER = b"AETHER-Q-CBDC/NOTE-HEADER/v1"
L_ID = b"AETHER-Q-CBDC/NOTE-ID/v1"
L_REST = b"AETHER-Q-CBDC/NOTE-REST/v1"
L_CLAIM = b"AETHER-Q-CBDC/NOTE-CLAIM/v1"
L_ROOT = b"AETHER-Q-CBDC/BATCH-ROOT/v1"
L_CERT = b"AETHER-Q-CBDC/MINT-CERT/v1"
L_CONSTRAINTS = b"AETHER-Q-CBDC/CONSTRAINTS/v1"
L_MINT_AUTH = b"AETHER-Q-BANK/MINT-AUTH/v1"
L_WIRE = b"AETHER-Q-BANK/WIRE/v1"
L_KEYSTORE_AAD = b"AETHER-Q-BANK/KEYSTORE/v1"
L_SRV_ID = b"AETHER-Q-v5.1-SRV-ID"

# §3.2 sonlar
NOMINALLAR: tuple[int, ...] = (5000, 1000, 500, 100, 50, 10, 5, 1)
MAX_KUPYURA = 100_000
XAZINA = "AQ-TREASURY"
YADRO_UZ = 56
MUHR_UZ = 72
PARTIYA_ID_UZ = 16
SIR_UZ = 32
SERT_ID_UZ = 16
BOLAK_QATOR = 250
MAX_XABAR = 1_048_576

ML_DSA_PK_UZ = 1952
ML_DSA_IMZO_UZ = 3309

BATCH_MAGIC = "AETHER-Q-CBDC-BATCH"
BATCH_VERSION = 1
CERT_FORMAT = "AETHER-Q-CBDC-CERT"
