"""Generate firmware/qv_model.h (weights) and firmware/qv_vectors.h (golden vectors)."""
from __future__ import annotations

from pathlib import Path

import numpy as np

from .meter import ATTACKS, FEATURES, N_FEATURES, dataset
from .model import LAYERS, QuantAE

N_NORMAL, N_PER_ATTACK = 300, 40


def cfloat(v: float) -> str:
    """C float literal that round-trips float32 exactly (never ``1f``)."""
    return f"{float(np.float32(v)):.9e}f"


def _arr(ctype: str, name: str, vals, fmt=str, per_line: int = 8) -> str:
    vals = [fmt(v) for v in np.asarray(vals).ravel()]
    lines = [", ".join(vals[i : i + per_line]) for i in range(0, len(vals), per_line)]
    return f"static const {ctype} {name}[{len(vals)}] = {{\n    " + ",\n    ".join(lines) + "\n};\n"


def model_header(q: QuantAE) -> str:
    out = [
        "/* Generated by qoravul.tinyml.export_c -- do not edit. */",
        "#ifndef QV_MODEL_H",
        "#define QV_MODEL_H",
        "#include <stdint.h>",
        "",
        f"#define QV_N_IN {N_FEATURES}",
        f"#define QV_N_LAYERS {len(q.layers)}",
        f"#define QV_MAX_WIDTH {max(LAYERS)}",
        f"#define QV_THRESHOLD {int(q.threshold)}",
        f"static const int qv_dims[{len(LAYERS)}] = {{{', '.join(map(str, LAYERS))}}};",
        f"/* features: {', '.join(FEATURES)} */",
        f"static const float qv_s_in = {cfloat(q.s_in)};",
        _arr("float", "qv_mean", q.mean, cfloat, 4),
        _arr("float", "qv_std", q.std, cfloat, 4),
        _arr("int32_t", "qv_feat_thresh", q.feat_thresh),
        _arr("int16_t", "qv_env_lo", q.env_lo),
        _arr("int16_t", "qv_env_hi", q.env_hi),
    ]
    for i, L in enumerate(q.layers):
        out.append(_arr("int8_t", f"qv_w{i}", L["w"], per_line=16))
        out.append(_arr("int32_t", f"qv_b{i}", L["b"]))
    out.append("static const int8_t *const qv_w[QV_N_LAYERS] = {" + ", ".join(f"qv_w{i}" for i in range(len(q.layers))) + "};")
    out.append("static const int32_t *const qv_b[QV_N_LAYERS] = {" + ", ".join(f"qv_b{i}" for i in range(len(q.layers))) + "};")
    out.append(_arr("int32_t", "qv_m0", [L["m0"] for L in q.layers]))
    out.append(_arr("int8_t", "qv_sh", [L["sh"] for L in q.layers]))
    out.append(_arr("uint8_t", "qv_relu", [int(L["relu"]) for L in q.layers]))
    out += ["#endif /* QV_MODEL_H */", ""]
    return "\n".join(out)


def golden_vectors(seed: int = 4242) -> tuple[np.ndarray, list[str]]:
    """300 normal + 40 per attack, shuffled deterministically."""
    xs, labels = [dataset(n=N_NORMAL, seed=seed)], ["normal"] * N_NORMAL
    for i, att in enumerate(ATTACKS):
        xs.append(dataset(n=N_PER_ATTACK, seed=seed + 1 + i, attack=att))
        labels += [att] * N_PER_ATTACK
    x = np.concatenate(xs).astype(np.float32)
    perm = np.random.default_rng(seed).permutation(len(x))
    return x[perm], [labels[i] for i in perm]


def vectors_header(q: QuantAE, x: np.ndarray) -> str:
    d = q.detect(x)
    n = len(x)
    out = [
        "/* Generated by qoravul.tinyml.export_c -- golden vectors from the Python reference. */",
        "#ifndef QV_VECTORS_H",
        "#define QV_VECTORS_H",
        "#include <stdint.h>",
        f"#define QV_N_VECTORS {n}",
        _arr("float", "qv_vec_x", x, cfloat, 4),
        _arr("int8_t", "qv_vec_xq", d["xq"], per_line=16),
        _arr("int8_t", "qv_vec_yq", d["yq"], per_line=16),
        _arr("int32_t", "qv_vec_score", d["score"]),
        _arr("uint8_t", "qv_vec_anomaly", d["anomaly"].astype(int), per_line=32),
        _arr("uint8_t", "qv_vec_culprit", d["culprit"], per_line=32),
        "#endif /* QV_VECTORS_H */",
        "",
    ]
    return "\n".join(out)


def export(q: QuantAE, outdir: str | Path = "firmware") -> dict:
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    x, labels = golden_vectors()
    (outdir / "qv_model.h").write_text(model_header(q))
    (outdir / "qv_vectors.h").write_text(vectors_header(q, x))
    return {"vectors": len(x), "anomalous": int(q.detect(x)["anomaly"].sum())}
