// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Namunaviy command (D1): summani nisbatlar bo'yicha bo'ladi.
	 *  Summa string sifatida keladi va Rustda parse qilinadi (frontend pul hisoblamaydi).
	 */
	allocateDemo: (totalMinor: string, ratios: number[]) => typedError<MoneyDto[], DemoError>(__TAURI_INVOKE("allocate_demo", { totalMinor, ratios })),
	vaultState: () => typedError<VaultStateDto, CommandError>(__TAURI_INVOKE("vault_state")),
	/**  Birinchi ishga tushirish: PIN o'rnatadi va bazani ochadi. */
	setupPin: (pin: string) => typedError<null, CommandError>(__TAURI_INVOKE("setup_pin", { pin })),
	unlock: (pin: string) => typedError<null, CommandError>(__TAURI_INVOKE("unlock", { pin })),
	lock: () => typedError<null, CommandError>(__TAURI_INVOKE("lock")),
	/**  Foydalanuvchi faolligi: avto-qulf hisoblagichini yangilaydi. */
	activity: () => typedError<null, CommandError>(__TAURI_INVOKE("activity")),
};

/* Types */
/**  Frontendga qaytadigan xatolar. Matnlarda summa, ism yoki PIN bo'lmaydi. */
export type CommandError = { kind: "InvalidPin" } | { kind: "WrongPin" } | { kind: "Locked"; retry_after_secs: number } | { kind: "NotInitialized" } | { kind: "AlreadyInitialized" } | { kind: "KeyringMissing" } | { kind: "Internal"; message: string };

export type DemoError = { kind: "InvalidInput"; message: string };

/**  Pul DTO (DESKTOP_PROMPT 3.2): `minor` JS 2^53 chegarasidan himoya uchun string. */
export type MoneyDto = {
	minor: string,
	currency: string,
	formatted: string,
};

export type VaultStateDto = { kind: "Uninitialized" } | { kind: "Locked"; retry_after_secs: number } | { kind: "Unlocked" };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

