// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Namunaviy command (D1): summani nisbatlar bo'yicha bo'ladi.
	 *  Summa string sifatida keladi va Rustda parse qilinadi (frontend pul hisoblamaydi).
	 */
	allocateDemo: (totalMinor: string, ratios: number[]) => typedError<MoneyDto[], DemoError>(__TAURI_INVOKE("allocate_demo", { totalMinor, ratios })),
	vaultState: () => typedError<VaultStateDto, CommandError>(__TAURI_INVOKE("vault_state")),
	/**  Birinchi ishga tushirish: PIN o'rnatadi va bazani ochadi. */
	setupPin: (pin: string) => typedError<null, CommandError>(__TAURI_INVOKE("setup_pin", { pin })),
	unlock: (pin: string) => typedError<null, CommandError>(__TAURI_INVOKE("unlock", { pin })),
	lock: () => typedError<null, CommandError>(__TAURI_INVOKE("lock")),
	/**  Foydalanuvchi faolligi: avto-qulf hisoblagichini yangilaydi. */
	activity: () => typedError<null, CommandError>(__TAURI_INVOKE("activity")),
	homeSummary: () => typedError<HomeDto, CommandError>(__TAURI_INVOKE("home_summary")),
	/**  Daromad summasi yozilganda darhol "shundan X so'm — kelajagingiz uchun". */
	suggestShare: (amountText: string) => typedError<SuggestionDto, CommandError>(__TAURI_INVOKE("suggest_share", { amountText })),
	recordIncome: (input: IncomeInput) => typedError<RecordedDto, CommandError>(__TAURI_INVOKE("record_income", { input })),
	listIncomes: (monthText: string) => typedError<IncomeDto[], CommandError>(__TAURI_INVOKE("list_incomes", { monthText })),
	setRule: (input: RuleInput) => typedError<null, CommandError>(__TAURI_INVOKE("set_rule", { input })),
	setOpeningBalance: (amountText: string) => typedError<MoneyDto, CommandError>(__TAURI_INVOKE("set_opening_balance", { amountText })),
	requestWithdrawal: (amountText: string, reason: string) => typedError<WithdrawalDto, CommandError>(__TAURI_INVOKE("request_withdrawal", { amountText, reason })),
	confirmWithdrawal: (id: string) => typedError<MoneyDto, CommandError>(__TAURI_INVOKE("confirm_withdrawal", { id })),
	cancelWithdrawal: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("cancel_withdrawal", { id })),
	listWithdrawals: () => typedError<WithdrawalDto[], CommandError>(__TAURI_INVOKE("list_withdrawals")),
	auditOverview: (monthText: string) => typedError<OverviewDto, CommandError>(__TAURI_INVOKE("audit_overview", { monthText })),
	auditSetCategory: (monthText: string, categoryId: string, amountText: string) => typedError<null, CommandError>(__TAURI_INVOKE("audit_set_category", { monthText, categoryId, amountText })),
	listObligations: () => typedError<ObligationDto[], CommandError>(__TAURI_INVOKE("list_obligations")),
	addObligation: (input: ObligationInput) => typedError<ObligationDto, CommandError>(__TAURI_INVOKE("add_obligation", { input })),
	addNasiya: (creditor: string, totalText: string) => typedError<ObligationDto, CommandError>(__TAURI_INVOKE("add_nasiya", { creditor, totalText })),
	payNasiya: (id: string, amountText: string) => typedError<MoneyDto, CommandError>(__TAURI_INVOKE("pay_nasiya", { id, amountText })),
	removeObligation: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("remove_obligation", { id })),
	journey: () => typedError<JourneyDto, CommandError>(__TAURI_INVOKE("journey")),
	chapterDetail: (id: string) => typedError<ChapterDetailDto, CommandError>(__TAURI_INVOKE("chapter_detail", { id })),
	setTaskDone: (chapterId: string, taskId: string, done: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("set_task_done", { chapterId, taskId, done })),
	savePage: (chapterId: string, body: string) => typedError<null, CommandError>(__TAURI_INVOKE("save_page", { chapterId, body })),
	setUnlockPolicy: (input: PolicyInput) => typedError<null, CommandError>(__TAURI_INVOKE("set_unlock_policy", { input })),
	listMembers: () => typedError<MemberDto[], CommandError>(__TAURI_INVOKE("list_members")),
	/**  Yangi a'zo. PIN berilsa, shu zahoti o'rnatiladi. */
	addMember: (name: string, role: string, pin: string | null) => typedError<MemberDto, CommandError>(__TAURI_INVOKE("add_member", { name, role, pin })),
	changeMemberPin: (memberId: string, oldPin: string | null, newPin: string) => typedError<null, CommandError>(__TAURI_INVOKE("change_member_pin", { memberId, oldPin, newPin })),
	listCategories: () => typedError<CategoryDto[], CommandError>(__TAURI_INVOKE("list_categories")),
	setNecessity: (categoryId: string, necessityText: string, memberId: string) => typedError<null, CommandError>(__TAURI_INVOKE("set_necessity", { categoryId, necessityText, memberId })),
	addCategory: (input: CategoryInput) => typedError<CategoryDto, CommandError>(__TAURI_INVOKE("add_category", { input })),
	setHabit: (categoryId: string, isHabit: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("set_habit", { categoryId, isHabit })),
	/**  «Hafta varag'i»: barcha qatorlar bitta tranzaksiyada. */
	addExpenses: (items: ExpenseInput[]) => typedError<number, CommandError>(__TAURI_INVOKE("add_expenses", { items })),
	listExpenses: (from: string, to: string) => typedError<ExpenseDto[], CommandError>(__TAURI_INVOKE("list_expenses", { from, to })),
	removeExpense: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("remove_expense", { id })),
	/**  Shu izoh bilan oxirgi yozilgan xarajat kategoriyasi (avtomatik to'ldirish uchun). */
	suggestCategory: (note: string) => typedError<string | null, CommandError>(__TAURI_INVOKE("suggest_category", { note })),
	havasReport: (monthText: string) => typedError<HavasDto, CommandError>(__TAURI_INVOKE("havas_report", { monthText })),
	/**  Yangi chegara taklif qiladi: taklif qiluvchi o'z PIN'ini kiritadi. */
	proposeLimit: (memberId: string, pin: string, amountText: string) => typedError<null, CommandError>(__TAURI_INVOKE("propose_limit", { memberId, pin, amountText })),
	/**  Har bir kattalar o'z PIN'i bilan rozilik beradi. */
	consentLimit: (limitId: string, memberId: string, pin: string) => typedError<null, CommandError>(__TAURI_INVOKE("consent_limit", { limitId, memberId, pin })),
	listTreats: () => typedError<TreatDto[], CommandError>(__TAURI_INVOKE("list_treats")),
	addTreat: (name: string, amountText: string, weekday: number) => typedError<null, CommandError>(__TAURI_INVOKE("add_treat", { name, amountText, weekday })),
	setTreatActive: (id: string, active: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("set_treat_active", { id, active })),
	removeTreat: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("remove_treat", { id })),
	logTreat: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("log_treat", { id })),
	habitStats: () => typedError<HabitDto[], CommandError>(__TAURI_INVOKE("habit_stats")),
	/**
	 *  Bayonnomani PDF qiladi va foydalanuvchi **OS «saqlash» oynasida** tanlagan joyga yozadi.
	 *  Fayl faqat Rust tomonida yoziladi (frontendga fayl tizimi ruxsati berilmaydi).
	 *  Foydalanuvchi bekor qilsa `None`; muvaffaqiyatda saqlangan fayl nomi.
	 */
	exportCouncilPdf: (monthText: string) => typedError<string | null, CommandError>(__TAURI_INVOKE("export_council_pdf", { monthText })),
};

/* Types */
export type BlockDto = {
	id: string,
	text: string,
	source: string | null,
	/**  Ulamo tekshiruvidan o'tmagan (faqat ishlab chiqish rejimida ko'rinadi). */
	unreviewed: boolean,
};

export type CategoryDto = {
	id: string,
	name: string,
	/**  `ZARUR` | `KERAK` | `HAVAS` | `None` (belgilanmagan). */
	necessity: string | null,
	is_charity: boolean,
	is_habit: boolean,
	/**  Oxirgi o'zgartirgan a'zo va sana: «Dilnoza, 2026-10-09». */
	last_change: string | null,
};

export type CategoryInput = {
	name: string,
	necessity: string | null,
	is_habit: boolean,
};

export type CategoryTotalDto = {
	category_id: string,
	name: string,
	owner: string | null,
	amount: MoneyDto,
};

export type ChapterDetailDto = {
	id: string,
	title: string,
	law: number,
	placeholder: boolean,
	blocks: BlockDto[],
	page_prompt: string,
	page_body: string,
	tasks: TaskDto[],
};

export type ChapterEntryDto = {
	id: string,
	title: string,
	law: number,
	order: number,
	opened: boolean,
	opened_on: string | null,
	is_current: boolean,
};

/**  Frontendga qaytadigan xatolar. Matnlarda summa, ism yoki PIN bo'lmaydi. */
export type CommandError = { kind: "InvalidPin" } | { kind: "WrongPin" } | { kind: "Locked"; retry_after_secs: number } | { kind: "NotInitialized" } | { kind: "AlreadyInitialized" } | { kind: "KeyringMissing" } | 
/**  Summa matni noto'g'ri (masalan, "12abc"). */
{ kind: "InvalidAmount" } | { kind: "Invalid"; message: string } | { kind: "NotFound" } | { kind: "InsufficientFunds" } | { kind: "OpeningBalanceExists" } | 
/**  A'zoning PIN'i noto'g'ri (havas chegarasiga rozilik). */
{ kind: "MemberWrongPin" } | { kind: "MemberPinLocked"; retry_after_secs: number } | { kind: "MemberNoPin" } | 
/**  "Kelajagim"dan pul olish pauzasi tugamagan. */
{ kind: "Cooling"; remaining_secs: number } | { kind: "Internal"; message: string };

export type DemoError = { kind: "InvalidInput"; message: string };

export type ExpenseDto = {
	id: string,
	date: string,
	category_id: string,
	amount: MoneyDto,
	channel: string,
	note: string | null,
	is_gift: boolean,
	is_ostentation: boolean,
	funded_by_debt: boolean,
};

export type ExpenseInput = {
	/**  `YYYY-MM-DD`. */
	date: string,
	category_id: string,
	amount: string,
	/**  `CASH` | `CARD`. */
	channel: string,
	note: string | null,
	/**  `None` — kategoriya toifasi. */
	necessity: string | null,
	is_gift: boolean,
	is_ostentation: boolean,
	funded_by_debt: boolean,
};

export type HabitDto = {
	category_id: string,
	name: string,
	window_total: MoneyDto,
	week: MoneyDto,
	month: MoneyDto,
	year: MoneyDto,
};

export type HavasDto = {
	month: string,
	/**  Faqat barcha kattalar rozi bo'lgan chegara. */
	limit: MoneyDto | null,
	pending: PendingLimitDto | null,
	spent: MoneyDto,
	/**  `OK` | `NEAR` | `OVER`; chegara faol bo'lmasa `None`. */
	state: string | null,
	used_bp: number | null,
	ostentation: MoneyDto,
	debt_funded: MoneyDto,
	charity: MoneyDto,
	gifts_excluded: MoneyDto,
};

export type HomeDto = {
	month: string,
	/**  Bugungi lokal sana (`YYYY-MM-DD`) va shu haftaning boshi (juma). */
	today: string,
	week_start: string,
	previous_month: string,
	self_paid: MoneyDto,
	/**  Oylik daromadga nisbatan, bazis punkt (500 = 5%). */
	self_paid_bp: number,
	income: MoneyDto,
	month_result: MoneyDto,
	vault_balance: MoneyDto,
	streak_weeks: number,
	best_streak_weeks: number,
	saved_days: number,
	rule: RuleDto,
	rate_suggestion_bp: number | null,
	pending_withdrawals: number,
};

export type IncomeDto = {
	id: string,
	source: string,
	channel: string,
	amount: MoneyDto,
	received_on: string,
};

export type IncomeInput = {
	/**  Foydalanuvchi yozgan summa (so'mda), Rustda parse qilinadi. */
	amount: string,
	/**  `DAILY_WORK` | `ORDER` | `SALARY` | `OTHER`. */
	source: string,
	/**  `CASH` | `CARD`. */
	channel: string,
	/**  `None` — taklif qilingan ulush. */
	share: string | null,
};

export type JourneyDto = {
	chapters: ChapterEntryDto[],
	current_id: string,
	current_title: string,
	opened_this_week: boolean,
	week_start: string,
	week_tasks: TaskDto[],
	week_done: number,
	unlock: UnlockDto | null,
	policy: PolicyDto,
};

export type MemberDto = {
	id: string,
	name: string,
	/**  `ADULT` | `CHILD` | `VIEWER`. */
	role: string,
	has_pin: boolean,
};

export type MemberRef = {
	id: string,
	name: string,
};

/**  Pul DTO (DESKTOP_PROMPT 3.2): `minor` JS 2^53 chegarasidan himoya uchun string. */
export type MoneyDto = {
	minor: string,
	currency: string,
	formatted: string,
};

export type ObligationDto = {
	id: string,
	name: string,
	/**  `RECURRING` | `NASIYA`. */
	kind: string,
	owner: string,
	amount: MoneyDto,
	due_day: number,
	creditor: string | null,
	remaining: MoneyDto | null,
};

export type ObligationInput = {
	name: string,
	amount: string,
	due_day: number,
	/**  `LANDLORD` | `BANK` | `SHOP` | `STATE` | `FUEL` | `OTHER`. */
	owner: string,
};

export type OverviewDto = {
	month: string,
	income: MoneyDto,
	obligations: MoneyDto,
	expenses: MoneyDto,
	savings: MoneyDto,
	month_result: MoneyDto,
	unexplained: MoneyDto,
	categories: CategoryTotalDto[],
	owners: OwnerShareDto[],
	self_paid_bp: number,
};

export type OwnerShareDto = {
	/**  `None` — o'zingiz bo'lmagan "boshqa"; egalar `LANDLORD`, `BANK`, `SHOP`, `STATE`, `FUEL`, `OTHER`. */
	owner: string | null,
	amount: MoneyDto,
	bp: number,
};

export type PendingLimitDto = {
	limit_id: string,
	amount: MoneyDto,
	consented: string[],
	/**  Hali rozi bo'lmagan kattalar: (ID, ism). */
	missing: MemberRef[],
};

export type PolicyDto = {
	window_weeks: number,
	min_satisfied_weeks: number,
	min_tasks_per_week: number,
};

export type PolicyInput = {
	window_weeks: number,
	min_satisfied_weeks: number,
	min_tasks_per_week: number,
};

export type RecordedDto = {
	income_id: string,
	share: MoneyDto,
	vault_balance: MoneyDto,
};

export type RuleDto = { kind: "Percent"; bp: number } | { kind: "MonthlyFixed"; target: MoneyDto };

export type RuleInput = {
	/**  `PERCENT` (value — bazis punkt, masalan "500") yoki `MONTHLY_FIXED` (value — so'mda summa). */
	kind: string,
	value: string,
};

export type SuggestionDto = {
	share: MoneyDto,
	allocated_this_month: MoneyDto,
	rule: RuleDto,
};

export type TaskDto = {
	id: string,
	title: string,
	done: boolean,
	/**  Ma'lumotdan avtomatik aniqlangan. */
	auto_detected: boolean,
	/**  Foydalanuvchi qo'lda belgilaydigan vazifa. */
	manual: boolean,
};

export type TreatDto = {
	id: string,
	name: string,
	amount: MoneyDto,
	/**  1 = dushanba ... 7 = yakshanba. */
	weekday: number,
	active: boolean,
	due_today: boolean,
	logged_today: boolean,
};

export type UnlockDto = {
	unlocked: boolean,
	satisfied_weeks: number,
	needed_weeks: number,
	/**  Hali birorta ham hafta tugamagan bo'lsa 0. */
	weeks_in_window: number,
};

export type VaultStateDto = { kind: "Uninitialized" } | { kind: "Locked"; retry_after_secs: number } | { kind: "Unlocked" };

export type WithdrawalDto = {
	id: string,
	amount: MoneyDto,
	reason: string,
	available_at: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

