[package]
name = "domain"
edition.workspace = true
version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
money = { version = "0.1.0", path = "../money" }
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
time = { version = "0.3.55", features = ["formatting", "parsing", "macros"] }
uuid = { version = "1.27.0", features = ["v7"] }

[lints]
workspace = true
